import { createClient } from '@/lib/supabase/server'
import { requireStaff } from '@/lib/auth'
import { hasPermission } from '@/lib/permissions'
import { formatDateTime } from '@/lib/utils'
import { isWhatsAppConfigured } from '@/lib/notifications'
import { asFormAction } from '@/lib/form-action'
import { retryNotification, dispatchPendingNotifications } from './actions'

const STATUS_STYLE: Record<string, string> = {
  sent: 'bg-green-50 text-green-700',
  pending: 'bg-amber-50 text-amber-700',
  failed: 'bg-red-50 text-red-700',
  skipped: 'bg-gray-100 text-gray-500',
}

const EVENT_LABEL: Record<string, string> = {
  order_created: 'Order created',
  order_status_changed: 'Order status',
  payment_success: 'Payment received',
  payment_failed: 'Payment failed',
  sample_requested: 'Sample request',
}

export default async function NotificationsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const profile = await requireStaff(['admin', 'operations', 'management', 'accounts', 'sales'])
  const supabase = await createClient()
  const [canView, canManage] = await Promise.all([
    hasPermission(supabase, profile, 'notifications.view'),
    hasPermission(supabase, profile, 'notifications.manage'),
  ])
  if (!canView) {
    return (
      <div className="mx-auto max-w-3xl rounded-2xl border border-gray-200 bg-white p-8 text-center text-sm text-gray-600">
        You do not have permission to view notifications.
      </div>
    )
  }

  const { status } = await searchParams
  let query = supabase
    .from('notification_outbox')
    .select('id, event_type, recipient_type, recipient_name, recipient_phone, rendered_message, status, attempts, last_error, created_at, sent_at')
    .order('created_at', { ascending: false })
    .limit(100)
  if (status && ['sent', 'pending', 'failed', 'skipped'].includes(status)) query = query.eq('status', status)
  const { data: rows } = await query
  const configured = isWhatsAppConfigured()

  return (
    <div className="mx-auto max-w-6xl space-y-6 pb-10">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Notifications</h1>
          <p className="mt-1 text-xs text-gray-500">WhatsApp messages generated by orders, payments and sample requests.</p>
        </div>
        {canManage ? (
          <form action={asFormAction(dispatchPendingNotifications)}>
            <button type="submit" className="rounded-lg border border-[#9C7A33] px-4 py-2 text-xs font-semibold text-[#9C7A33] hover:bg-[#9C7A33]/5">
              Send pending now
            </button>
          </form>
        ) : null}
      </div>

      <div className={`rounded-2xl border p-4 text-xs ${configured ? 'border-green-200 bg-green-50 text-green-800' : 'border-amber-200 bg-amber-50 text-amber-900'}`}>
        {configured ? (
          <p><span className="font-semibold">WhatsApp is connected.</span> New events are sent automatically.</p>
        ) : (
          <p>
            <span className="font-semibold">WhatsApp is not connected yet.</span> Messages are still generated and logged below as
            &ldquo;Skipped&rdquo; so nothing is lost. Add <span className="font-mono">WHATSAPP_ACCESS_TOKEN</span> and{' '}
            <span className="font-mono">WHATSAPP_PHONE_NUMBER_ID</span> to the environment to start sending.
          </p>
        )}
      </div>

      <div className="flex flex-wrap gap-2 text-[11px]">
        {['all', 'sent', 'pending', 'failed', 'skipped'].map((s) => (
          <a
            key={s}
            href={s === 'all' ? '/crm/notifications' : `/crm/notifications?status=${s}`}
            className={`rounded-full px-3 py-1 font-semibold capitalize ${(status || 'all') === s ? 'bg-[#9C7A33] text-white' : 'bg-gray-100 text-gray-600'}`}
          >
            {s}
          </a>
        ))}
      </div>

      <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white">
        <table className="w-full min-w-[760px] text-left text-xs">
          <thead className="bg-gray-50 text-[10px] uppercase text-gray-500">
            <tr>
              <th className="p-3">When</th>
              <th className="p-3">Event</th>
              <th className="p-3">Recipient</th>
              <th className="p-3">Message</th>
              <th className="p-3">Status</th>
              {canManage ? <th className="p-3" /> : null}
            </tr>
          </thead>
          <tbody>
            {(rows || []).map((r) => (
              <tr key={r.id} className="border-t border-gray-100 align-top">
                <td className="p-3 whitespace-nowrap text-gray-500">{formatDateTime(r.created_at)}</td>
                <td className="p-3">{EVENT_LABEL[r.event_type] || r.event_type}</td>
                <td className="p-3">
                  <p className="font-semibold text-gray-900">{r.recipient_name || '—'}</p>
                  <p className="text-gray-400">
                    {r.recipient_type === 'staff' ? 'Staff' : 'Customer'} · {r.recipient_phone ? `+${r.recipient_phone}` : 'no phone'}
                  </p>
                </td>
                <td className="p-3 max-w-[320px] text-gray-600">{r.rendered_message}</td>
                <td className="p-3">
                  <span className={`rounded-full px-2.5 py-0.5 text-[10px] font-semibold capitalize ${STATUS_STYLE[r.status] || STATUS_STYLE.skipped}`}>
                    {r.status}
                  </span>
                  {r.last_error ? <p className="mt-1 max-w-[220px] text-[10px] text-gray-400">{r.last_error}</p> : null}
                </td>
                {canManage ? (
                  <td className="p-3">
                    {r.status !== 'sent' && r.recipient_phone ? (
                      <form action={asFormAction(retryNotification)}>
                        <input type="hidden" name="id" value={r.id} />
                        <button type="submit" className="text-[11px] font-semibold text-[#9C7A33] hover:underline">
                          Retry
                        </button>
                      </form>
                    ) : null}
                  </td>
                ) : null}
              </tr>
            ))}
            {(rows || []).length === 0 ? (
              <tr>
                <td colSpan={canManage ? 6 : 5} className="p-8 text-center text-gray-400">No notifications yet.</td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>
    </div>
  )
}
